name: portvessel
version: "1.0.0"
config-version: 2

profile: portvessel

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  portvessel:
    staging:
      +schema: portvessel_dev_silver

    intermediate:
      +schema: portvessel_dev_silver

    geospatial:
      +schema: portvessel_dev_silver

    marts:
      +materialized: table
      +schema: portvessel_dev_marts
      +persist_docs:
        relation: true
        columns: true