project_id      = "cloudprojects-506123"
region          = "europe-west3"
environment     = "dev"
ingestion_image = "europe-west3-docker.pkg.dev/cloudprojects-506123/portvessel/ingestion:workflow-v2"
loader_image    = "europe-west3-docker.pkg.dev/cloudprojects-506123/portvessel/bq-loader:v2"
quality_image   = "europe-west3-docker.pkg.dev/cloudprojects-506123/portvessel/quality:v4"
alert_email     = "rk899866@gmail.com"